# Generated by Django 5.2.17 on 2026-09-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 4-4-2, 4-2-3-1, 4-3-3', max_length=50, unique=True)),
                ('code', models.CharField(help_text='Short key e.g. 442, 4231, 433', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief notes about this tactical setup.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Check to display this formation on the public site.')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.CharField(blank=True, help_text="Path to image inside static folder e.g., 'images/players/player1.jpg'", max_length=255, null=True),
        ),
    ]
