# Generated by Django 5.2.17 on 2026-09-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_formation_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='layout',
            field=models.JSONField(default=list, help_text='Enter row counts from defense to attack, e.g., [4, 4, 2] for 4-4-2 or [4, 2, 3, 1] for 4-2-3-1'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='code',
            field=models.CharField(help_text='Short key e.g. 442, 4231', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='name',
            field=models.CharField(help_text='e.g. 4-4-2, 4-2-3-1', max_length=50, unique=True),
        ),
    ]
