# Generated by Django 5.2.17 on 2026-09-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_formation_layout_alter_formation_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='layout',
        ),
        migrations.AddField(
            model_name='formation',
            name='formation_format',
            field=models.CharField(default='4-4-2', help_text='Enter formation in any format you like, e.g. 4-4-2, 4-3-3, or 4-2-3-1', max_length=50),
        ),
        migrations.AlterField(
            model_name='formation',
            name='name',
            field=models.CharField(help_text='e.g. 4-4-2, 4-2-3-1, 4-3-3', max_length=50, unique=True),
        ),
    ]
