# Generated by Django 5.2.17 on 2026-09-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_formation_layout_formation_formation_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C'), ('D', 'Group D'), ('E', 'Group E'), ('F', 'Group F')], default='A', max_length=1)),
                ('team_name', models.CharField(max_length=100)),
                ('played', models.PositiveIntegerField(default=0)),
                ('won', models.PositiveIntegerField(default=0)),
                ('drawn', models.PositiveIntegerField(default=0)),
                ('lost', models.PositiveIntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=1)),
                ('is_ocean_stars', models.BooleanField(default=False, help_text='Check if this team is Ocean Stars FC')),
            ],
            options={
                'ordering': ['group_name', 'position'],
            },
        ),
        migrations.RemoveField(
            model_name='formation',
            name='formation_format',
        ),
        migrations.AlterField(
            model_name='formation',
            name='code',
            field=models.CharField(help_text='Type layout format numbers here e.g. 4-4-2, 4-3-3, or 4-2-3-1', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='description',
            field=models.TextField(blank=True, help_text='Brief tactical notes.', null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check to display on public site.'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='name',
            field=models.CharField(help_text='e.g. 4-4-2, 4-2-3-1', max_length=50, unique=True),
        ),
    ]
